apiVersion: v1
kind: Pod
metadata:
  name: dail-journal-pod
  namespace: web-application
spec:
  containers:
    - name: web-appilacation-container
      image: danish1234512/your-image-name
      ports:
        - containerPort: 3000
    

