apiVersion: v1
kind: Service
metadata:
  name: dail-journal-services
spec:
  selector:
    app: journal-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
